{% set name = "pytest-httpserver" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d896a6556e426240837891b0552040ed4148e393ddf63f675b60d47bcd2d3f39

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - werkzeug

test:
  imports:
    - pytest_httpserver
  requires:
    - pip
    - pytest
    - requests
  source_files:
    - tests
  commands:
    - python -m pytest -v -ra tests
    - python -m pip check

about:
  home: https://github.com/csernazs/pytest-httpserver
  dev_url: https://github.com/csernazs/pytest-httpserver
  doc_url: https://pytest-httpserver.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest-httpserver is a httpserver for pytest
  description: |
    This library is designed to help to test http clients without contacting
    the real http server.  In other words, it is a fake http server which is
    accessible via localhost can be started with the pre-defined expected
    http requests and their responses.

extra:
  recipe-maintainers:
    - duncanmmacleod
