{% set name = "pytest-httpserver" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c14600b8efb9ea8d7e63251a242ab987f13028b36d3d397ffaca3c929f67eb16

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - python >=3.8
    - werkzeug >=2.0.0

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=7.1.3
    - requests >=2.28.1
    - toml
    - types-toml >=0.10.8
  commands:
    - python -m pip check
    - python -m pytest -v -ra tests -k 'not ipv6'

about:
  home: https://github.com/csernazs/pytest-httpserver
  dev_url: https://github.com/csernazs/pytest-httpserver
  doc_url: https://pytest-httpserver.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest-httpserver is a httpserver for pytest
  description: |
    This library is designed to help to test http clients without contacting
    the real http server.  In other words, it is a fake http server which is
    accessible via localhost can be started with the pre-defined expected
    http requests and their responses.

extra:
  recipe-maintainers:
    - duncanmmacleod
